### ISSUE TITLE
test command doesn't use filter

### ISSUE THREAD

**Issue by Necroskillz** [Janus-vistaprint/gulp-dotnet-cli#10]
The `test` task has `filter` property in the configuration model, but the arg builder doesn't actually use it when generating the command. Also there is a wrong text in the docs for this option.

**Comment by TerribleDev** [comment]
Hi, thanks for the issue. I see you have already dug into the issue a little bit. Would you like to submit a PR, or would you just like us to fix the issue.

**Comment by Necroskillz** [comment]
Sure I can do a PR

**Comment by TerribleDev** [comment]
👍 thanks for the PR. Fixed in `0.4.1`
