### ISSUE TITLE
dont  load appsettings.json config .

### ISSUE THREAD

**Issue by zsensi** [Janus-vistaprint/gulp-dotnet-cli#16]
Dont load appsettings.json config.

```
gulp.task('run:api', function (cb) {
    return gulp.src('api.csproj', { cwd: 'D:\\sources', read: false })
        .pipe(dotnetCli.run()); // not work for appsettings.json config.
});
```

Add cwd: file.cwd in shelly.js
cp.spawn(command, calculatedArgs, { **cwd: file.cwd**, stdio: 'inherit' })

that's done.

**Comment by TerribleDev** [comment]
That implementation will break the other tasks, such as build, etc. We should always keep the current working directory to be the root. However I agree that on dotnet run we should set the current working directory to the root path of the file.

**Comment by TerribleDev** [comment]
Oh wait sorry it won't break things I didn't see the first part

**Comment by TerribleDev** [comment]
@zsensi instead of making you explicitly set the cwd. Instead do you think it would be better for us to just default the cwd to the root of the folder containing the csproj?

**Comment by TerribleDev** [comment]
@lucax88x /cc

**Comment by zsensi** [comment]
I want to run another site that's place to outside of cwd dir.   example, my project work dir is : 
D:\\project\
   site.csproj
  gulpfile.js 
  appsettings.json

Another project site dir is:
D:\\sources\
  api.csproj
  appsettings.json

the gulpfile.js has a task :  
```
  gulp.task('run:api', () => {
     return gulp.src('api.csproj', { cwd: 'D:\\sources', read: false })
         .pipe(dotnetCli.run()); //here load D:\\project\appsettings.json, but not load D:\\sources\appsettings.json
 });
```

**Comment by TerribleDev** [comment]
right, so I think the actual fix is to set the current working directory to the root of the csproj you are about to run `dotnet run` on. That way you don't have to actually explicitly set the cwd, and would allow for globbing of csproj's
