### ISSUE TITLE
can't able to convert nuget package

### ISSUE THREAD

**Issue by jayaprakashkamaraj** [Janus-vistaprint/gulp-dotnet-cli#25]
While using below gulp task we can't able to convert nugget package,

```
gulp.task('pack', ['build'], () => {
    console.log(process.cwd());
    return gulp.src('src/*.csproj', { read: false })
        .pipe(pack({
            output: 'output',
            version: version,
            echo: true, noRestore: 'normal'
        }));
});
```

**Comment by TerribleDev** [comment]
Interesting, what is the error you get? Have you tried updating your modules to 1.0.2?

**Comment by jayaprakashkamaraj** [comment]
yes, i have updated 1.0.2... but nuget doesn't generated in given path 

like:.... process.cwd() + 'output';

can you please tell me what is the reason for this problem.

**Comment by TerribleDev** [comment]
Does path.resolve(process.cwd(), 'output') solve the problem

**Comment by TerribleDev** [comment]
You may have to require path

**Comment by jayaprakashkamaraj** [comment]
Thanks ... i have tried that also but still facing the same problem...

`gulp.task('pack', ['build'], () => {
    console.log(process.cwd());
    return gulp.src('src/*.csproj', { read: false })
        .pipe(pack({
            output: path.resolve(process.cwd(), 'nupkgs') , 
            version: version,
            echo: true, noRestore: false
        }));
});`

**Comment by TerribleDev** [comment]
it seems to work fine for me see: https://github.com/TerribleDev/gulp-dotnet-cli-testing my nupkg's are being output to the output root folder

it would help if you can make a simple git repository with the reproducible problem.

**Comment by jayaprakashkamaraj** [comment]
Issue in my side please close this ticket
