### ISSUE TITLE
Add a way to call `dotnet watch run`

### ISSUE THREAD

**Issue by PonchoPowers** [Janus-vistaprint/gulp-dotnet-cli#29]
At the moment you can trigger `dotnet run` but you can't trigger `dotnet watch run`.

I have watchers that transpile my less and typescript files but I can't invoke the same for the csharp files.

It would be good to provide this functionality, if possible?

My preference would be something like:
```
gulp.task("watch", gulp.series(function watchTask() {
    return gulp.src(config.projectFilePath, { read: false })
        .pipe(dotnet.run({watch:true}));
}));
```

**Comment by TerribleDev** [comment]
are you sure thats the right solution, and not to instead make the regular `dotnet run` command work with gulp's watcher? I'd assume a more gulp-y approach would be to make the dotnet run work so you can have gulp watch files and kick the process, but then also compile whatever front-end code, or other tasks you need.

Thoughts?

**Comment by TerribleDev** [comment]
@Matthew-Bonner ^

**Comment by TerribleDev** [comment]
Closed due to inactivity
