### ISSUE TITLE
Log actual cli commands

### ISSUE THREAD

**Issue by alex-bello** [Janus-vistaprint/gulp-dotnet-cli#6]
Is there a way to write the actual cli commands to the console? If not, would it be possible to add that as an optional parameter? 

Thanks!

**Comment by TerribleDev** [comment]
@alex-bello its not currently a feature, but I'm sure we could add it. 

Would it be acceptable if you had to ask for it for each action.

For example:


```javascript
let {restore, build} = require('gulp-dotnet-cli');

gulp.task('restore', ()=>{
  return gulp.src('**/*.csproj')
                    .pipe(restore({echo: true}));
});

gulp.task('build', ['restore'], ()=>{
  return gulp.src('**/*.csproj')
                    .pipe(build({echo: true}));
});


```

**Comment by TerribleDev** [comment]
My one concern is that, if we just enable it someone might accidentally console log their api keys on the push command.

**Comment by TerribleDev** [comment]
@cubsk thoughts?

**Comment by cubsk** [comment]
As long as it defaults to not printing them, I'm fine. It would be useful for debugging.

**Comment by TerribleDev** [comment]
Hi @alex-bello we added the echo flag in v0.3.0

You should be able to add the echo flag to each action to see the command printed out to the console.

**Comment by alex-bello** [comment]
That's better than I was thinking! Thanks for the quick response!

**Comment by TerribleDev** [comment]
@alex-bello np
