### ISSUE TITLE
Support for 1.0.0-preview2-1-003177 SDK

### ISSUE THREAD

**Issue by alex-bello** [Janus-vistaprint/gulp-dotnet-cli#8]
Unfortunately, one of my clients is not able to upgrade to VS2017 anytime soon and they do not qualify for VS2017 Community Edition. That means we are stuck using the `1.0.0-preview2-1-003177` SDK for the near future. 

I have forked this project and made changes to the commands and models to support the previous SDK version. That got me thinking that perhaps it might not be a bad idea, especially going forward, to build in support for different SDKs in this package. You could have it search the root folder for a global.json and then based on the value, use/exclude commands from the model. 

I can certainly understand if you don't see it as a benefit as I can always continue using the fork I made.

Thanks, Al

**Comment by TerribleDev** [comment]
Hmm, I'd think that we would only want to do this for "Released" versions of the dotnet cli, and since 1.0.0-preview2 is not released I don't think it wouldn't be worth supporting. I also don't anticipate any breaking changes to the cli in version 2, for us to go ahead and start working on this ability. In the future if there are breaking changes we will definitely make this feature happen.


Just curious, what broke between preview2, and 1.x?

**Comment by TerribleDev** [comment]
P.S. We'll always take PR's if you can think up a good way to have people pass in versions and get all the actions back, for a given SDK. I'm sure we'd take in the work.

For example you could do something like...

```javascript
var {build, test} = require('gulp-dotnet-cli').Version('1.0.0-preview2');


```

**Comment by TerribleDev** [comment]
I'd totally take something like that in, we'd have to make sure the folder structure was quite sane, and maybe do some organizations. 

each sdk could have its own folder of models, builders, and actions. and inside that folder could be an index.js file that returns the actions for the sdk of the folder name

for example

```

| lib
| -- sdks
| -- sdks / 1.0.0 / models
| -- sdks / 1.0.0 / builders
| -- sdks / 1.0.0 / build.js
| -- sdks / 1.0.0 / index.js

```

sdks / 1.0.0 / index.js would look like:

```
modules.export = {build: require('./build.js'), test: require('./test.js');
```

at the very root of the project we could have an index.js file that looked like this:

```javascript

var default = require('./sdks/1.0.0');
default.Version = (version)=>{
  return require(`./sdks/${version}`);
};
module.exports = default;

```

**Comment by TerribleDev** [comment]
Basically, what I'm saying is....

We probably wouldn't put in the work ourselves to support preview2, but we would take in a PR if it was suitable to support multiple SDK's.

**Comment by alex-bello** [comment]
I think 1.0.0 was when MS decided to drop project.json and switch to csproj/MSBuild. We had already started a few projects and were making good progress (not to mention dropped cash on VS2015) when they switched to csproj, which VS2015 doesn't support. I had just convinced 
management to finally pay to upgrade everyone from VS2010.

I like your thought process, it's much cleaner than my original idea. I can start working on that and send a PR at some point. 

Thanks for your help.

**Comment by TerribleDev** [comment]
np, did you try contacting msft? if you explain your situation they may be willing to convert those '15 to '17 licenses since you didn't buy them that long ago. Especially since they made a breaking change last minute.

These days I use VS Code exclusively. I'm not a fan of visual studio.

**Comment by alex-bello** [comment]
I talked to the team and they're exploring investing in MSDN licenses for all of the developers, not just a few. Hopefully, that means we won't have to deal with this again in the future. I'm going to close this issue as you all have addressed my questions very well. If it's decided we are not going to upgrade, I'll do the work and put in a PR. Thanks again!

**Comment by TerribleDev** [comment]
No problem @alex-bello glad to hear you are going to be ok!
